## YAML Template.
---
version: '3.9'

services:
  java_app:
    container_name: helado-api
    image: helado-api-app:1.0.0
    build: .
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/mydb
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=mypassword
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: mydb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: